apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pipeline
  region: us-west-1

managedNodeGroups:
  - name: primary
    instanceType: t2.medium
    minSize: 2
    maxSize: 4
    spot: true
    ssh:
      allow: true
      publicKeyPath: CaliforniaKeyPair
