--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deploy
spec:
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: maven-app-deploy
        image: bjgomes/maven:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8085
--- 
apiVersion: v1
kind: Service
metadata:
  name: maven-app-svc
spec:
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

  
  